### ISSUE TITLE
parameters.tf is mentioned in all docs, but does not exist

### ISSUE THREAD

**Issue by timothymeyers** [azurenoops/ref-scca-enclave-landing-zone-starter#16]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Nearly (if not) all of the `0X-*.md` files in `docs/` reference a `parameters.tfvars` file that does not exist and link to it, resulting in 404s.

`.gitignore` is configured to ignore `*.tfvars` files, so it makes sense that it would be missing/overlooked.

### Any log messages given by the failure
>

### Expected/desired behavior

I think it would be better to have a `parameters.tfvars.template` file with simple defaults and parameters that need to be updated obviously commented.

Then, the docs could have a section or table that describes how the template file is laid out, with links to the terraform registry docs for the modules used.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jrspinella** [comment]
fixed OBE
