### ISSUE TITLE
Update Team Charter and Create Developer Onboarding Presentation

### ISSUE THREAD

**Issue by STG5326** [azurenoops/ref-scca-enclave-landing-zone-starter#34]
Matt Ross to update the charter. Schedule a one-hour call with Spins and SSJ for next Thursday August 10th.

**Comment by matross-gh** [comment]
Update the charter on the team's decision about branch naming using scaled trunk-based development.

**Comment by sstjean** [comment]
Is this Issue a duplicate of https://github.com/orgs/azurenoops/projects/1?pane=issue&itemId=35011848 ?

**Comment by jrspinella** [comment]
This is a dup, closing
