### ISSUE TITLE
Private AKS Cluster

### ISSUE THREAD

**Issue by cheruvu1** [azurenoops/ref-scca-enclave-landing-zone-starter#37]
Deployed to/with a SCCA Spoke Network. 
The AKS need to have SCCA compliant which is:
 
	1. **Private AKS Cluster - Completed.** 
	2. Policy enabled  - Work in Progress.
	3. Enable Log Analytics
	4. Key Vault to manage keys
	5. Private API server
	7. Private endpoints and DNS
	8. Role based Access to API server

**Comment by cheruvu1** [comment]
1. **Private AKS Cluster - Completed.**

**Comment by jrspinella** [comment]
Closing for issue [#20](https://github.com/azurenoops/terraform-azurerm-overlays-kubernetes/issues/20)
