### ISSUE TITLE
TEST CASE - Deploy LZ Starter to MAG, Multi-Subscription, using Terraform CLI, Remote State Storage

### ISSUE THREAD

**Issue by timothymeyers** [azurenoops/ref-scca-enclave-landing-zone-starter#45]
This issue is a test case for landing zone starter deployment.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] test case
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
### Test steps

0. (Optionally) Create a branch (or Fork) for testing
1. Clone repository to your local computer (or into a Codespace)
1. `cd <cloned-dir>/infrastructure/terraform`
1. `cp ../../tfvars/parameters.tfvars .`
1. `terraform version` (should be version >= 1.4.6)
1. [Authenticate Terraform with Azure](https://learn.microsoft.com/en-us/azure/developer/terraform/authenticate-to-azure?tabs=bash). Note that authenticating with Azure Government requires the use of the ARM_ENVIRONMENT environment variable and `az cloud set`
1. Configure Terraform for [Remote state storage](https://learn.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=azure-cli). A helper script `az-remote-backend.sh` is described in [this doc](https://github.com/azurenoops/ref-scca-enclave-landing-zone-starter/blob/main/docs/00-Remote-State-Storage.md), but YMMV.
3. `terraform init`
4. `terraform plan -out test.plan`
5. `terraform apply -f test.plan`

### Other helpful details

**Comment by jrspinella** [comment]
Test Successful with v4.0.0-beta1
