### ISSUE TITLE
Strong Review of TERRAFORM-GITHUB-ACTIONS Repository

### ISSUE THREAD

**Issue by matross-gh** [azurenoops/ref-scca-enclave-landing-zone-starter#59]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Navigate to https://github.com/azurenoops/terraform-github-actions

### Any log messages given by the failure
None

### Expected/desired behavior
Plain Language

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

Strongly suggest removal, or renaming, of .github/workflows/github_sucks.md file in the repository

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JohnBreault** [comment]
File was updated 9 months ago. closing issue
