### ISSUE TITLE
Parameter File tfvars/parameters.tfvars Not Found

### ISSUE THREAD

**Issue by matross-gh** [azurenoops/ref-scca-enclave-landing-zone-starter#60]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Sign-In to your GitHub account
2. Navigate to https://github.com/azurenoops/ref-scca-enclave-landing-zone-starter
3. Click on Fork, then + Create a new fork
4. Complete the Fork process and navigate back to your GitHub overview page
5. Review ref-scca-enclave-landing-zone-starter is displayed on your overview page and is forked from azurenoops/ref-scca-enclave-landing-zone-starter

### Any log messages given by the failure
1. File not found tfvars/parameters.tfvars when trying to execute terraform plan workflow

### Expected/desired behavior
1. Workflow to create the plan executes

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

The following change allowed the workflow to execute:
      - name: terraform plan
        uses: azurenoops/terraform-github-actions/terraform-plan@v1.34.2
        with:
          path: **/home/runner/work/ref-scca-enclave-landing-zone-starter/ref-scca-enclave-landing-zone-starter/infrastructure/terraform**
          variables: |
            subscription_id_hub               = "${{ env.ARM_SUBSCRIPTION_ID }}"           
          var_file: **/home/runner/work/ref-scca-enclave-landing-zone-starter/ref-scca-enclave-landing-zone-starter/infrastructure/terraform/tfvars/parameters.tfvars**
          backend_config: |
            storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
            container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}            
            resource_group_name=${{ secrets.TFSTATE_RG }}

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jrspinella** [comment]
This has been changed in #62 to use the full path of the src.
