### ISSUE TITLE
No Value for VM_ADMIN_PASSWORD in variables.devsecops.tf

### ISSUE THREAD

**Issue by matross-gh** [azurenoops/ref-scca-enclave-landing-zone-starter#61]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Sign-In to your GitHub account
2. Navigate to https://github.com/azurenoops/ref-scca-enclave-landing-zone-starter
3. Click on Fork, then + Create a new fork
4. Complete the Fork process and navigate back to your GitHub overview page
5. Review ref-scca-enclave-landing-zone-starter is displayed on your overview page and is forked from azurenoops/ref-scca-enclave-landing-zone-starter

### Any log messages given by the failure
Error: No value for required variable

  on variables.devsecops.tf line 71:
  71: variable "vm_admin_password" {

The root module input variable "vm_admin_password" is not set, and has no
default value. Use a -var or -var-file command line argument to provide a
value for this variable.

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

Suggesting, or something similar and place into Key Vault

resource "random_password" "password" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_db_instance" "example" {
  instance_class    = "db.t3.micro"
  allocated_storage = 64
  engine            = "mysql"
  username          = "someone"
  password          = random_password.password.result
}

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jrspinella** [comment]
#65 

Added VM_PAssword as a secret to the workflows. If not using workflows, you need to add it to the cli string:

terraform plan --var-file ../../tfvars/parameters.tfvars --var "default_location=usgovvirginia" --var "subscription_id_hub=<<subid>>" --var "vm_admin_password=P@ssword1234!" --var "environment=usgovernment" --out "anoa.dev.plan"
